import type { Metadata } from "next";
import {Inter, Geist, Geist_Mono } from "next/font/google";
// import Sidebar from "@/components/layout/Sidebar";
import Topbar from "@/components/layout/Topbar";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/Sidebar";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable:'--font-inter',
  subsets:['latin'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   const cookieStore = await cookies();
  const user = cookieStore.get('user')?.value;
  let user_;
  if(user){
    user_ = JSON.parse(user).roleId;
  }

  // console.log('user is',user);

  return (
    <html lang="en"  suppressHydrationWarning>
      <body
        className={` ${inter.variable} antialiased `}
      >
        <SidebarProvider>
          <Topbar/>
          {/* <Sidebar/> */}
          <AppSidebar role={user_}/>
          <div className='mt-[104px] ml-[55px]'>
          {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}

